### ISSUE TITLE
Can't import exported csv files

### ISSUE THREAD

**Issue by FirstWithThisName** [brodeurlv/fastnfitness#266]
**Can't Import Data**
When I try to import to import data and select a file the app crashes, without error message and closes.
I checked it with the latest commit from my android studio build and the current f-droid version.
I also checked that the app has permission to enabled in the settings.

**To Reproduce**
1. Import Data
2. Select an exported csv file.

**Expected behavior**
Import the data from the csv file.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A10
 - OS: Android 11

**Additional context**
logcat:
```
2023-04-22 01:13:30.138 18552-18552 SurfaceControl          com.easyfitness.debug                I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0x2f84607 / android.view.SurfaceControl.readFromParcel:1121 android.view.IWindowSession$Stub$Proxy.relayout:1824 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2023-04-22 01:13:30.140 18552-18552 ViewRootIm...nActivity] com.easyfitness.debug                I  Relayout returned: old=(0,0,720,1520) new=(0,0,720,1520) req=(720,1520)8 dur=12 res=0x5 s={false 0} ch=false fn=-1
2023-04-22 01:13:33.255 18552-18552 SurfaceControl          com.easyfitness.debug                I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0x4016683 / android.view.SurfaceControl.readFromParcel:1121 android.view.IWindowSession$Stub$Proxy.relayout:1814 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2023-04-22 01:13:33.258 18552-18552 SurfaceControl          com.easyfitness.debug                I  assignNativeObject: nativeObject = 0 Surface(name=null)/@0x2f84607 / android.view.SurfaceControl.readFromParcel:1121 android.view.IWindowSession$Stub$Proxy.relayout:1824 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
2023-04-22 01:13:33.263 18552-18552 ViewRootIm...nActivity] com.easyfitness.debug                I  Relayout returned: old=(0,0,720,1520) new=(0,0,720,1520) req=(720,1520)4 dur=11 res=0x1 s={false 0} ch=false fn=-1
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1993)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.content.ContentResolver.openInputStream(ContentResolver.java:1485)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at com.easyfitness.MainActivity.onActivityResult(MainActivity.java:1026)
2023-04-22 01:13:33.316 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.ActivityThread.deliverResults(ActivityThread.java:5564)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5612)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.os.Looper.loop(Looper.java:246)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at android.app.ActivityThread.main(ActivityThread.java:8625)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at java.lang.reflect.Method.invoke(Native Method)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
2023-04-22 01:13:33.317 18552-18552 System.err              com.easyfitness.debug                W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-04-22 01:13:33.320 18552-18552 AndroidRuntime          com.easyfitness.debug                D  Shutting down VM
2023-04-22 01:13:33.327 18552-18552 AndroidRuntime          com.easyfitness.debug                E  FATAL EXCEPTION: main
                                                                                                    Process: com.easyfitness.debug, PID: 18552
                                                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/msf:15370 flg=0x43 }} to activity {com.easyfitness.debug/com.easyfitness.MainActivity}: java.lang.NullPointerException
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5571)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5612)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8625)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at java.io.Reader.<init>(Reader.java:78)
                                                                                                    	at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
                                                                                                    	at com.csvreader.CsvReader.<init>(CsvReader.java:178)
                                                                                                    	at com.easyfitness.DAO.export.CVSManager.importDatabase(CVSManager.java:438)
                                                                                                    	at com.easyfitness.MainActivity.onActivityResult(MainActivity.java:1032)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5564)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5612) 
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2317) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8625) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
2023-04-22 01:13:33.357 18552-18552 Process                 com.easyfitness.debug                I  Sending signal. PID: 18552 SIG: 9
```

**Comment by maximilianovermeyer** [comment]
Not solving the issue, but maybe helpful as a workaround:
For me it helped to export the settings on the target device, then switching out the files with the ones from the source device. I could then import without any problems.

**Comment by FirstWithThisName** [comment]
I got a new Phone and migrated without a problem, don't know what the problem has been.
